// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn5NIsAP65v9ABBPkUL4YD84bwuJYN8L8',
    appId: '1:811862823354:web:2ddb8451284e5c1d840d83',
    messagingSenderId: '811862823354',
    projectId: 'volet-5e728',
    authDomain: 'volet-5e728.firebaseapp.com',
    storageBucket: 'volet-5e728.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTCI99mv8CXtx4pTo8M62M2z4O2xAtfdc',
    appId: '1:811862823354:android:43b0a7b30628a967840d83',
    messagingSenderId: '811862823354',
    projectId: 'volet-5e728',
    storageBucket: 'volet-5e728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi9pdJPHpk00BmHCWw5DMBPHl5_FkAQ6o',
    appId: '1:811862823354:ios:bf597a5f9437beea840d83',
    messagingSenderId: '811862823354',
    projectId: 'volet-5e728',
    storageBucket: 'volet-5e728.firebasestorage.app',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi9pdJPHpk00BmHCWw5DMBPHl5_FkAQ6o',
    appId: '1:811862823354:ios:bf597a5f9437beea840d83',
    messagingSenderId: '811862823354',
    projectId: 'volet-5e728',
    storageBucket: 'volet-5e728.firebasestorage.app',
    iosBundleId: 'com.example.wallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn5NIsAP65v9ABBPkUL4YD84bwuJYN8L8',
    appId: '1:811862823354:web:bdbae8df0444462d840d83',
    messagingSenderId: '811862823354',
    projectId: 'volet-5e728',
    authDomain: 'volet-5e728.firebaseapp.com',
    storageBucket: 'volet-5e728.firebasestorage.app',
  );
}
